sudo: required
services: 
    - docker

before_install:
    - docker build -t milostoster80/docker-react -f Dockerfile.dev .    

script:
    - docker run -e CI=true milostoster80/docker-react npm run test -- --coverage
    